[package]
name = "plunk"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {  path = "../common" }

serde = {version = "1.0.219" , features = ["derive"]}
tokio = {version = "1.44.2" , features = ["full"]}
reqwest = "0.12.15"
serde_json = "1.0.140"
dotenv = "0.15.0"
log = "0.4.27"